name: 'Predict Issue Labels'
description: 'Predicts issue labels using a machine learning model trained against existing issues.'

inputs:
  issues_model:
    description: "The path to the issues model file."
    required: true
    default: "labeler-cache/issues-model.zip"
  issue_numbers:
    description: 'The issue numbers to predict labels for, specified as a comma-separated list of numbers or number ranges.'
    required: true
  pulls_model:
    description: "The path to the pulls model file."
    required: true
    default: "labeler-cache/pulls-model.zip"
  pull_numbers:
    description: 'The pull request numbers to predict labels for, specified as a comma-separated list of numbers or number ranges.'
    required: true
  label_prefix:
    description: "The label prefix used for prediction. Must end with a non-alphanumeric character."
    required: true
  threshold:
    description: "The minimum confidence score for a label prediction, as a decimal between 0.00 and 1.00. The recommended threshold is 0.40."
    required: true
  default_label:
    description: "The default label to apply if no prediction meets the threshold. Leave blank for no default label."

branding:
  color: "purple"
  icon: "tag"

runs:
  using: docker
  image: docker://ghcr.io/jeffhandley/issue-labeler/predictor:main
