name: "Predict Labels"
description: "Predict labels for Issues and Pull Requests using models already restored from cache."

inputs:
  issues:
    description: "Issue Numbers (comma-separated list of ranges)."
    required: true

  pulls:
    description: "Pull Request Numbers (comma-separated list of ranges)."
    required: true

  label_prefix:
    description: "The label prefix used for prediction. Must end with a non-alphanumeric character. Defaults to 'area-'."
    required: false
    default: "area-"

  threshold:
    description: "The minimum confidence score for a label prediction, as a decimal between 0.00 and 1.00. Defaults to 0.40."
    required: false
    default: "0.40"

  default_label:
    description: "The default label to apply if no prediction meets the threshold. Leave blank for no default label."

  excluded_authors:
    description: "Comma-separated list of authors to exclude. Defaults to none."

  retries:
    description: "Comma-separated list of retry delays in seconds. Defaults to '30,30,300,300,3000,3000'."
    required: false
    default: "30,30,300,300,3000,3000"

  test:
    description: "Run in test mode, outputting predictions without applying labels."
    required: false

  verbose:
    description: "Enable verbose output."
    required: false

branding:
  color: "purple"
  icon: "tag"

runs:
  using: docker
  # Reference the docker container image using a published sha256 digest
  # to ensure an immutable version is always used.
  image: docker://ghcr.io/dotnet/issue-labeler/predictor@sha256:<sha256-digest-to-be-added-here-after-first-release>
  env:
    INPUT_ISSUES_MODEL: "labeler-cache/issues-model.zip"
    INPUT_PULLS_MODEL: "labeler-cache/pulls-model.zip"
