name: 'Predict Issue Labels'
description: 'Predicts issue labels using a machine learning model trained against existing issues.'

inputs:
  issues:
    description: 'The issue numbers to predict labels for, specified as a comma-separated list of numbers or number ranges.'
    required: true
  pulls:
    description: 'The pull request numbers to predict labels for, specified as a comma-separated list of numbers or number ranges.'
    required: true
  label_prefix:
    description: "The label prefix used for prediction. Must end with a non-alphanumeric character."
    required: true
  threshold:
    description: "The minimum confidence score for a label prediction, as a decimal between 0.00 and 1.00. The recommended threshold is 0.40."
    required: true
  default_label:
    description: "The default label to apply if no prediction meets the threshold. Leave blank for no default label."
  excluded_authors:
    description: "Comma-separated list of authors to exclude."
  retries:
    description: "Comma-separated list of retry delays in seconds. Defaults to: 30,30,300,300,3000,3000."
  test:
    description: "Run in test mode, outputting predictions without applying labels."
  verbose:
    description: "Enable verbose output."

branding:
  color: "purple"
  icon: "tag"

runs:
  using: docker
  image: docker://ghcr.io/jeffhandley/issue-labeler/predictor:main
  env:
    INPUT_ISSUES_MODEL: "labeler-cache/issues-model.zip"
    INPUT_PULLS_MODEL:  "labeler-cache/pulls-model.zip"
