name: "Labeler: Promote Model"
description: "Promote a trained model to be active, backing up the currently active model."

inputs:
  type:
    description: "The model to promote. Must be 'issues' or 'pulls'."
    required: true
  staged_key:
    description: "The suffix for the staged cache entry to promote."
    required: true
  backup_key:
    description: "The suffix for the backup cache entry. This cache entry must not exist if there is an active entry to back up."
    required: true

branding:
  color: "purple"
  icon: "arrow-up"

runs:
  using: "composite"
  steps:
    - name: "Validate Inputs"
      shell: bash
      run: |
        if [[ "${{ inputs.type }}" != "issues" && "${{ inputs.type }}" != "pulls" ]]; then
          echo "::error::'type' must be either 'issues' or 'pulls'. Value provided: '${{ inputs.type }}'"
          echo ":x: **ERROR**" >> $GITHUB_STEP_SUMMARY
          echo "\`type\` must be either 'issues' or 'pulls'." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

        if [[ -z "${{ inputs.staged_key }}" || ! "${{ inputs.staged_key }}" =~ ^[a-zA-Z0-9/_\-]+$ ]]; then
          echo "::error::'staged_key' must be non-empty and contain only alphanumeric characters, hyphens, underscores, or slashes. Value provided: '${{ inputs.staged_key }}'"
          echo ":x: **ERROR**" >> $GITHUB_STEP_SUMMARY
          echo "\`staged_key\` must be non-empty and contain only alphanumeric characters, hyphens, underscores, or slashes. Value provided: '${{ inputs.staged_key }}'" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

        if [[ -z "${{ inputs.backup_key }}" || ! "${{ inputs.backup_key }}" =~ ^[a-zA-Z0-9/_\-]+$ ]]; then
          echo "::error::'backup_key' must be non-empty and contain only alphanumeric characters, hyphens, underscores, or slashes. Value provided: '${{ inputs.backup_key }}'"
          echo ":x: **ERROR**" >> $GITHUB_STEP_SUMMARY
          echo "\`backup_key\` must be non-empty and contain only alphanumeric characters, hyphens, underscores, or slashes. Value provided: '${{ inputs.backup_key }}'" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

        if [[ "${{ inputs.staged_key }}" == "ACTIVE" || "${{ inputs.backup_key }}" == "ACTIVE" || "${{ inputs.staged_key }}" == "${{ inputs.backup_key }}" ]]; then
          echo "::error::The 'staged_key' and 'backup_key' values must be different and cannot be 'ACTIVE'."
          echo ":x: **ERROR**" >> $GITHUB_STEP_SUMMARY
          echo "The \`staged_key\` and \`backup_key\` values must be different and cannot be 'ACTIVE'." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

    - name: "Set Environment Variables"
      shell: bash
      run: |
        echo "CACHE_PATH=labeler-cache/${{ inputs.type }}-model.zip" >> $GITHUB_ENV
        echo "staged_KEY=issue-labeler/model/${{ inputs.type }}/${{ inputs.staged_key }}" >> $GITHUB_ENV
        echo "ACTIVE_KEY=issue-labeler/model/${{ inputs.type }}/ACTIVE" >> $GITHUB_ENV
        echo "BACKUP_KEY=issue-labeler/model/${{ inputs.type }}/${{ inputs.backup_key }}" >> $GITHUB_ENV

    - name: "Check for existing staged cache entry"
      id: check-staged
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ env.staged_KEY }}
        lookup-only: true
        fail-on-cache-miss: true

    - name: "Check for existing backup cache entry"
      if: ${{ steps.check-staged.outputs.cache-hit == 'true' }}
      id: check-backup
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ env.BACKUP_KEY }}
        lookup-only: true
        fail-on-cache-miss: false

    - name: "Restore existing active cache entry"
      if: ${{ steps.check-staged.outputs.cache-hit == 'true' }}
      id: check-active
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ env.ACTIVE_KEY }}
        fail-on-cache-miss: false

    - name: "Abort if backup cache entry already exists"
      if: ${{ steps.check-active.outputs.cache-hit == 'true' && steps.check-backup.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        echo "::error::Backup cache key '${{ env.BACKUP_KEY }}' already exists. Cannot proceed with promotion."
        echo ":x: **ERROR**" >> $GITHUB_STEP_SUMMARY
        echo "Backup cache key \`${{ env.BACKUP_KEY }}\` already exists. Cannot proceed with promotion." >> $GITHUB_STEP_SUMMARY
        echo ""  >> $GITHUB_STEP_SUMMARY
        echo "> [!TIP]" >> $GITHUB_STEP_SUMMARY
        echo "> Either use a different \`backup_key\` value or delete the existing cache entry from the [Action Caches](/${{ github.repository }}/actions/caches) page and run the workflow again." >> $GITHUB_STEP_SUMMARY
        exit 1

    - name: "Cache backup of current active cache entry"
      if: ${{ steps.check-active.outputs.cache-hit == 'true' }}
      id: backup-file
      uses: actions/cache/save@v4
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ env.BACKUP_KEY }}

    - name: "Remove local copy of current active cache entry"
      if: ${{ steps.check-active.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        rm ${{ env.CACHE_PATH }}

    - name: "Restore the staged cache entry to promote"
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ env.staged_KEY }}
        fail-on-cache-miss: true

    - name: "Delete existing active cache entry"
      if: ${{ steps.check-active.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        gh api --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/actions/caches?key=${{ env.ACTIVE_KEY }}
      env:
        GH_TOKEN: ${{ github.token }}

    - name: "Save the staged cache entry as the active cache entry"
      uses: actions/cache/save@v4
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ env.ACTIVE_KEY }}

    - name: "Write summary"
      shell: bash
      run: |
        echo "> [!NOTE]" >> $GITHUB_STEP_SUMMARY
        echo "> The ${{ inputs.type }} model was promoted from '${{ inputs.staged_key }}' to 'ACTIVE'." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [[ "${{ steps.check-active.outputs.cache-hit }}" == "true" ]]; then
          echo "> [!NOTE]" >> $GITHUB_STEP_SUMMARY
          echo "> The previous 'ACTIVE' ${{ inputs.type }} model was backed up as '${{ inputs.backup_key }}'." >> $GITHUB_STEP_SUMMARY
          echo "> If the previous model needs to be restored, promote '${{ inputs.backup_key }}' and supply a different \`backup_key\`." >> $GITHUB_STEP_SUMMARY
        fi
