name: "Restore prediction model from cache"
description: "Restore an active model from cache for prediction or cache-retention."

inputs:
  type:
    description: "The model to promote. Must be 'issues' or 'pulls'."
    required: true

  cache_key:
    description: "The cache key suffix to use for loading the model. Defaults to 'ACTIVE'."
    required: true
    default: "ACTIVE"

  retention:
    description: "The action has been invoked to ensure cache retention"

branding:
  color: "purple"
  icon: "arrow-down"

runs:
  using: "composite"
  steps:
    - name: "Validate Inputs"
      shell: bash
      run: |
        if [[ "${{ inputs.type }}" != "issues" && "${{ inputs.type }}" != "pulls" ]]; then
          echo "::error::'type' must be either 'issues' or 'pulls'. Value provided: '${{ inputs.type }}'"
          echo ":x: **ERROR**" >> $GITHUB_STEP_SUMMARY
          echo "\`type\` must be either 'issues' or 'pulls'." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

    - name: "Restore model from cache"
      uses: actions/cache/restore@v4
      with:
        path: labeler-cache/${{ inputs.type }}-model.zip
        key: issue-labeler/model/${{ inputs.type }}/${{ inputs.cache_key || 'ACTIVE' }}
        fail-on-cache-miss: true

    - name: "Show summary for retention"
      if: ${{ inputs.retention }}
      shell: bash
      run: |
        echo "> [!NOTE]" >> $GITHUB_STEP_SUMMARY
        echo "> The ${{ inputs.type }} model was successfully restored from cache." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "> [!TIP]" >> $GITHUB_STEP_SUMMARY
        echo "> Refer to the [GitHub documentation](https://docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy) for more information about cache retention policies." >> $GITHUB_STEP_SUMMARY
