name: "Restore prediction model from cache"
description: "Restore an active model from cache for prediction or cache-retention."

inputs:
  type:
    description: "The model to promote. Must be 'issues' or 'pulls'."
    required: true

  cache_key:
    description: "The cache key suffix to use for loading the model. Defaults to 'ACTIVE'."
    required: true
    default: "ACTIVE"

branding:
  color: "purple"
  icon: "arrow-down"

runs:
  using: "composite"
  steps:
    - name: "Validate Inputs"
      shell: bash
      run: |
        if [[ "${{ inputs.type }}" != "issues" && "${{ inputs.type }}" != "pulls" ]]; then
          echo "Invalid type: ${{ inputs.type }}. Must be 'issues' or 'pulls'."
          exit 1
        fi

    - name: "Restore model from cache"
      uses: actions/cache/restore@v4
      with:
        path: labeler-cache/${{ inputs.type }}-model.zip
        key: issue-labeler/model/${{ inputs.type }}/${{ inputs.cache_key || 'ACTIVE' }}
        fail-on-cache-miss: true
