name: "Restore active model from cache"
description: "Restore an active model from cache for prediction or cache-retention."

inputs:
  model:
    description: "The model to promote. Must be 'issues' or 'pulls'."
    required: true

  cache_key:
    description: "The cache key suffix to use for loading the model. Defaults to 'ACTIVE'."
    required: true
    default: "ACTIVE"

branding:
  color: "purple"
  icon: "arrow-down"

runs:
  using: "composite"
  steps:
    - name: "Validate Inputs"
      shell: bash
      run: |
        if [[ "${{ inputs.model }}" != "issues" && "${{ inputs.model }}" != "pulls" ]]; then
          echo "Invalid model: ${{ inputs.model }}. Must be 'issues' or 'pulls'."
          exit 1
        fi

    - name: "Restore model from cache"
      uses: actions/cache/restore@v4
      with:
        path: labeler-cache/${{ inputs.model }}-model.zip
        key: issue-labeler/model/${{ inputs.model }}/${{ inputs.cache_key || 'ACTIVE' }}
        fail-on-cache-miss: true
