# CI Build and Test of the IssueLabeler solution
name: "CI Build"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci-*.yml"
      - "IssueLabeler/**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Set up the .NET SDK"
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 9.0.x

      - name: "Build the IssueLabeler solution"
        run: dotnet build IssueLabeler/ --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Set up the .NET SDK"
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 9.0.x

      - name: "Run tests from the IssueLabeler solution"
        run: dotnet test IssueLabeler/
